/* -*- js-indent-level: 8 -*- */
/*
 * Copyright the Collabora Online contributors.
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/// <reference path="./refs/globals.ts" />
/// <reference path="./sources.ts" />
/// <reference path="./helper/canvasContainerSetup.ts" />
/// <reference path="./helper/rectUtil.ts" />
/// <reference path="helper/Events.ts"/>
/// <reference path="./helper/util.ts"/>
/// <reference path="./data/LOUtilTestData.ts"/>
/// <reference path="./data/SheetGeometryTestData.ts" />
/// <reference path="./data/NativeBridgeTestData.ts" />
/// <reference path="../src/app/NativeBridge.ts" />
/// <reference path="../src/app/WriterAiArticleRegistry.ts" />
/// <reference path="../src/app/WriterAiCatalog.ts" />
/// <reference path="../src/app/CalcAiCatalog.ts" />
/// <reference path="../src/app/CalcAiContext.ts" />
/// <reference path="../src/app/MobileAiUiCatalog.ts" />
/// <reference path="../src/app/MobileNativeToolbar.ts" />
/// <reference path="../src/app/MobileDocTheme.ts" />
/// <reference path="../src/app/MobileAiBridge.ts" />
/// <reference path="../src/app/WriterAiController.ts" />
/// <reference path="../src/app/CalcAiMutateApply.ts" />
/// <reference path="../src/app/CalcAiController.ts" />
/// <reference path="../src/app/FormatBatchProcessor.ts" />
/// <reference path="../src/app/MobileAiFormatBatchDialog.ts" />
/// <reference path="../src/app/MobileSelectionEvents.ts" />
/// <reference path="../src/app/MobileAiImageDialog.ts" />
/// <reference path="../src/app/MobileSelectionMenuIcons.ts" />
/// <reference path="../src/app/MobileSelectionMenu.ts" />
/// <reference path="../src/app/WriterQuickActionBar.ts" />
/// <reference path="../src/app/MobileAiConversationController.ts" />
/// <reference path="../src/app/MobileAiSheet.ts" />
/// <reference path="../src/app/MobileAiTaskDialogLayout.ts" />
/// <reference path="../src/app/MobileAiWaiDropdown.ts" />
/// <reference path="../src/app/WriterAiArticleRegistry.ts" />
/// <reference path="../src/app/MobileAiArticleGenerateDialog.ts" />
/// <reference path="../src/app/MobileAiAssistantPanel.ts" />
/// <reference path="../src/app/MobileAiOperationIcons.ts" />
/// <reference path="../src/app/MobileAiOperationSheet.ts" />
/// <reference path="../src/app/MobileAiOperationDialog.ts" />
/// <reference path="../src/app/MobileAiTypesetDialog.ts" />
/// <reference path="../src/app/MobileAiDocumentExtractor.ts" />
/// <reference path="../src/app/TypesetSectionParser.ts" />
/// <reference path="../src/app/TypesetPreviewHtml.ts" />
/// <reference path="../src/app/TypesetBridge.ts" />
/// <reference path="../src/app/MobileAiCalcDialog.ts" />
/// <reference path="../src/app/MobileAiTranslateDialog.ts" />
/// <reference path="../src/app/MobileAiResultRenderer.ts" />
/// <reference path="../src/app/MobileAiConfiguration.ts" />
/// <reference path="../src/app/WriterAiPanel.ts" />
/// <reference path="../src/app/WriterEditorCatalog.ts" />
/// <reference path="../src/app/WriterEditorController.ts" />
/// <reference path="../src/app/WriterEditorWatermarkDialog.ts" />
/// <reference path="../src/app/WriterEditorSheet.ts" />
/// <reference path="../src/app/WriterEditorInlineSubpage.ts" />
/// <reference path="../src/app/CalcEditorBorder.ts" />
/// <reference path="../src/app/CalcEditorShapeDialog.ts" />
/// <reference path="../src/app/CalcEditorHyperlinkDialog.ts" />
/// <reference path="../src/app/CalcEditorDataValidationDialog.ts" />
/// <reference path="../src/app/CalcEditorValidationCatalog.ts" />
/// <reference path="../src/app/CalcEditorValidationBridge.ts" />
/// <reference path="../src/app/WriterEditorIcons.ts" />
/// <reference path="../src/app/WriterEditorPanel.ts" />
/// <reference path="../src/app/ImpressEditorCatalog.ts" />
/// <reference path="../src/app/ImpressEditorHyperlinkDialog.ts" />
/// <reference path="../src/app/ImpressTransitionBridge.ts" />
/// <reference path="../src/app/ImpressEditorPanel.ts" />
/// <reference path="../src/app/CalcEditorCatalog.ts" />
/// <reference path="../src/app/CalcEditorPanel.ts" />
/// <reference path="../src/app/WriterEditorChooseDialog.ts" />
/// <reference path="../src/app/WriterFindReplaceDialog.ts" />
/// <reference path="../src/app/WriterEditorInsertTableDialog.ts" />
/// <reference path="../src/app/WriterEditorImageDialog.ts" />
/// <reference path="../src/app/WriterEditorCommentDialog.ts" />
/// <reference path="../src/app/WriterEditorShapeCatalog.ts" />
/// <reference path="../src/app/WriterEditorShapeIcons.ts" />
/// <reference path="../src/app/WriterEditorShapeDialog.ts" />
/// <reference path="../src/app/WriterEditorChartPreviewIcons.ts" />
/// <reference path="../src/app/WriterEditorChartDialog.ts" />
/// <reference path="../src/app/WriterEditorPaperSizeDialog.ts" />
/// <reference path="../src/app/MobileWriterComments.ts" />
/// <reference path="../src/app/ImpressSolidColorCatalog.ts" />
/// <reference path="../src/app/MobileToolbarColorPicker.ts" />
/// <reference path="../src/app/WriterColorPickerDialog.ts" />
/// <reference path="../src/app/WriterCharPanel.ts" />
/// <reference path="../src/app/WriterParagraphPanel.ts" />
/// <reference path="../src/app/WriterWordCountSheet.ts" />
/// <reference path="../src/app/WriterSpellingSheet.ts" />

/// <reference path="./CanvasSectionContainer.test.ts" />
/// <reference path="./CBounds.test.ts" />
/// <reference path="./CPointSet.test.ts" />
/// <reference path="./Events.test.ts" />
/// <reference path="./LOUtil.test.ts" />
/// <reference path="./Rectangle.test.ts" />
/// <reference path="./SheetGeometry.test.ts" />
/// <reference path="./Util.test.ts" />
/// <reference path="./ViewLayout.test.ts" />
/// <reference path="./ServerCommand.test.ts" />
/// <reference path="./MobileAiBridge.test.ts" />
/// <reference path="./WriterAiCatalog.test.ts" />
/// <reference path="./CalcAiCatalog.test.ts" />
/// <reference path="./MobileAiUiCatalog.test.ts" />
/// <reference path="./MobileAiOperationSheet.test.ts" />
/// <reference path="./MobileNativeToolbar.test.ts" />
/// <reference path="./WriterAiController.test.ts" />
/// <reference path="./WriterAiIntegration.test.ts" />
/// <reference path="./WriterAiUiButtons.test.ts" />
/// <reference path="./CalcAiController.test.ts" />
/// <reference path="./MobileAiConversationController.test.ts" />
/// <reference path="./MobileAiDocumentExtractor.test.ts" />
/// <reference path="./MobileAiOperationDialog.test.ts" />
/// <reference path="./WriterEditorCatalog.test.ts" />
/// <reference path="./ImpressEditorCatalog.test.ts" />
/// <reference path="./CalcEditorCatalog.test.ts" />
/// <reference path="./MobileEditorFeatureDispatch.test.ts" />
/// <reference path="./WriterFindReplaceDialog.test.ts" />
/// <reference path="./WriterEditorController.test.ts" />
/// <reference path="./WriterEditorShapeCatalog.test.ts" />
/// <reference path="./FormatBatchProcessor.test.ts" />
/// <reference path="./MobileAiImageDialog.test.ts" />
/// <reference path="./MobileSelectionEvents.test.ts" />
// NOTE: reference new tests here ...
/// <reference path="./MobileSelectionMenu.test.ts" />
/// <reference path="./MobileWriterComments.test.ts" />
/// <reference path="./WriterParagraphPanel.test.ts" />
/// <reference path="./WriterWordCountSheet.test.ts" />
/// <reference path="./WriterSpellingSheet.test.ts" />
/// <reference path="./WriterFunctionSheet.test.ts" />
/// <reference path="./TypesetSectionParser.test.ts" />
/// <reference path="./TypesetBridge.test.ts" />
