/* Auto-generated by scripts/generate-impress-shape-assets.js — do not edit by hand. */

interface WriterEditorShapeEntry {
	index: number;
	unoCommand: string;
}

interface WriterEditorShapeSection {
	title: string;
	entries: (WriterEditorShapeEntry | null)[];
}

const WRITER_EDITOR_SHAPE_SECTIONS: WriterEditorShapeSection[] = [
	{
		title: "线条和箭头",
		entries: [
			{ index: 1, unoCommand: ".uno:Line" },
			{ index: 2, unoCommand: ".uno:LineArrowEnd" },
			{ index: 3, unoCommand: ".uno:LineCircleArrow" },
			{ index: 4, unoCommand: ".uno:LineSquareArrow" },
			{ index: 5, unoCommand: ".uno:LineArrows" },
			{ index: 6, unoCommand: ".uno:LineArrowStart" },
			{ index: 7, unoCommand: ".uno:LineArrowCircle" },
			{ index: 8, unoCommand: ".uno:LineArrowSquare" },
			{ index: 9, unoCommand: ".uno:MeasureLine" },
			{ index: 10, unoCommand: ".uno:Line_Diagonal" },
			{ index: 11, unoCommand: ".uno:Line" }
		]
	},
	{
		title: "曲线和多边形",
		entries: [
			{ index: 12, unoCommand: ".uno:BezierFill" },
			{ index: 13, unoCommand: ".uno:Polygon" },
			{ index: 14, unoCommand: ".uno:Polygon_Diagonal" },
			{ index: 15, unoCommand: ".uno:Freeline" },
			{ index: 16, unoCommand: ".uno:Bezier_Unfilled" },
			{ index: 17, unoCommand: ".uno:Polygon_Unfilled" },
			{ index: 18, unoCommand: ".uno:Polygon_Diagonal_Unfilled" },
			{ index: 19, unoCommand: ".uno:Freeline_Unfilled" },
			null,
			null,
			null,
			null
		]
	},
	{
		title: "连接符",
		entries: [
			{ index: 24, unoCommand: ".uno:ConnectorArrowEnd" },
			{ index: 25, unoCommand: ".uno:ConnectorLineArrowEnd" },
			{ index: 26, unoCommand: ".uno:ConnectorCurveArrowEnd" },
			{ index: 27, unoCommand: ".uno:ConnectorLinesArrowEnd" },
			{ index: 28, unoCommand: ".uno:Connector" },
			{ index: 29, unoCommand: ".uno:ConnectorLine" },
			{ index: 30, unoCommand: ".uno:ConnectorCurve" },
			{ index: 31, unoCommand: ".uno:ConnectorLines" },
			{ index: 32, unoCommand: ".uno:ConnectorArrows" },
			{ index: 33, unoCommand: ".uno:ConnectorLineArrows" },
			{ index: 34, unoCommand: ".uno:ConnectorCurveArrows" },
			{ index: 35, unoCommand: ".uno:ConnectorLinesArrows" }
		]
	},
	{
		title: "基本形状",
		entries: [
			{ index: 36, unoCommand: ".uno:BasicShapes.rectangle" },
			{ index: 37, unoCommand: ".uno:BasicShapes.round-rectangle" },
			{ index: 38, unoCommand: ".uno:BasicShapes.quadrat" },
			{ index: 39, unoCommand: ".uno:BasicShapes.round-quadrat" },
			{ index: 40, unoCommand: ".uno:BasicShapes.parallelogram" },
			{ index: 41, unoCommand: ".uno:BasicShapes.trapezoid" },
			{ index: 42, unoCommand: ".uno:BasicShapes.ellipse" },
			{ index: 43, unoCommand: ".uno:BasicShapes.circle" },
			{ index: 44, unoCommand: ".uno:BasicShapes.circle-pie" },
			{ index: 45, unoCommand: ".uno:CircleCut" },
			{ index: 46, unoCommand: ".uno:Arc" },
			{ index: 47, unoCommand: ".uno:BasicShapes.block-arc" },
			{ index: 48, unoCommand: ".uno:BasicShapes.isosceles-triangle" },
			{ index: 49, unoCommand: ".uno:BasicShapes.right-triangle" },
			{ index: 50, unoCommand: ".uno:BasicShapes.diamond" },
			{ index: 51, unoCommand: ".uno:BasicShapes.pentagon" },
			{ index: 52, unoCommand: ".uno:BasicShapes.hexagon" },
			{ index: 53, unoCommand: ".uno:BasicShapes.octagon" },
			{ index: 54, unoCommand: ".uno:BasicShapes.can" },
			{ index: 55, unoCommand: ".uno:BasicShapes.cube" },
			{ index: 56, unoCommand: ".uno:BasicShapes.paper" },
			{ index: 57, unoCommand: ".uno:BasicShapes.cross" },
			{ index: 58, unoCommand: ".uno:BasicShapes.frame" },
			{ index: 59, unoCommand: ".uno:BasicShapes.ring" }
		]
	},
	{
		title: "符号形状",
		entries: [
			{ index: 60, unoCommand: ".uno:SymbolShapes.smiley" },
			{ index: 61, unoCommand: ".uno:SymbolShapes.heart" },
			{ index: 62, unoCommand: ".uno:SymbolShapes.sun" },
			{ index: 63, unoCommand: ".uno:SymbolShapes.moon" },
			{ index: 64, unoCommand: ".uno:SymbolShapes.cloud" },
			{ index: 65, unoCommand: ".uno:SymbolShapes.lightning" },
			{ index: 66, unoCommand: ".uno:SymbolShapes.flower" },
			{ index: 67, unoCommand: ".uno:SymbolShapes.forbidden" },
			{ index: 68, unoCommand: ".uno:SymbolShapes.puzzle" },
			{ index: 69, unoCommand: ".uno:SymbolShapes.quad-bevel" },
			{ index: 70, unoCommand: ".uno:SymbolShapes.octagon-bevel" },
			{ index: 71, unoCommand: ".uno:SymbolShapes.diamond-bevel" },
			{ index: 72, unoCommand: ".uno:SymbolShapes.bracket-pair" },
			{ index: 73, unoCommand: ".uno:SymbolShapes.left-bracket" },
			{ index: 74, unoCommand: ".uno:SymbolShapes.right-bracket" },
			{ index: 75, unoCommand: ".uno:SymbolShapes.brace-pair" },
			{ index: 76, unoCommand: ".uno:SymbolShapes.left-brace" },
			{ index: 77, unoCommand: ".uno:SymbolShapes.right-brace" }
		]
	},
	{
		title: "箭头总汇",
		entries: [
			{ index: 78, unoCommand: ".uno:ArrowShapes.right-arrow" },
			{ index: 79, unoCommand: ".uno:ArrowShapes.left-arrow" },
			{ index: 80, unoCommand: ".uno:ArrowShapes.down-arrow" },
			{ index: 81, unoCommand: ".uno:ArrowShapes.up-arrow" },
			{ index: 82, unoCommand: ".uno:ArrowShapes.left-right-arrow" },
			{ index: 83, unoCommand: ".uno:ArrowShapes.up-down-arrow" },
			{ index: 84, unoCommand: ".uno:ArrowShapes.circular-arrow" },
			{ index: 85, unoCommand: ".uno:ArrowShapes.s-sharped-arrow" },
			{ index: 86, unoCommand: ".uno:ArrowShapes.split-arrow" },
			{ index: 87, unoCommand: ".uno:ArrowShapes.split-round-arrow" },
			{ index: 88, unoCommand: ".uno:ArrowShapes.quad-arrow" },
			{ index: 89, unoCommand: ".uno:ArrowShapes.corner-right-arrow" },
			{ index: 90, unoCommand: ".uno:ArrowShapes.chevron" },
			{ index: 91, unoCommand: ".uno:ArrowShapes.pentagon-right" },
			{ index: 92, unoCommand: ".uno:ArrowShapes.striped-right-arrow" },
			{ index: 93, unoCommand: ".uno:ArrowShapes.up-right-down-arrow" },
			{ index: 94, unoCommand: ".uno:ArrowShapes.notched-right-arrow" },
			{ index: 95, unoCommand: ".uno:ArrowShapes.up-right-arrow" },
			{ index: 96, unoCommand: ".uno:ArrowShapes.right-arrow-callout" },
			{ index: 97, unoCommand: ".uno:ArrowShapes.left-arrow-callout" },
			{ index: 98, unoCommand: ".uno:ArrowShapes.down-arrow-callout" },
			{ index: 99, unoCommand: ".uno:ArrowShapes.up-arrow-callout" },
			{ index: 100, unoCommand: ".uno:ArrowShapes.left-right-arrow-callout" },
			{ index: 101, unoCommand: ".uno:ArrowShapes.up-down-arrow-callout" },
			{ index: 102, unoCommand: ".uno:ArrowShapes.quad-arrow-callout" },
			{ index: 103, unoCommand: ".uno:ArrowShapes.up-right-arrow-callout" },
			null,
			null,
			null,
			null
		]
	},
	{
		title: "流程图",
		entries: [
			{ index: 108, unoCommand: ".uno:FlowChartShapes.flowchart-process" },
			{ index: 109, unoCommand: ".uno:FlowChartShapes.flowchart-alternate-process" },
			{ index: 110, unoCommand: ".uno:FlowChartShapes.flowchart-decision" },
			{ index: 111, unoCommand: ".uno:FlowChartShapes.flowchart-data" },
			{ index: 112, unoCommand: ".uno:FlowChartShapes.flowchart-predefined-process" },
			{ index: 113, unoCommand: ".uno:FlowChartShapes.flowchart-internal-storage" },
			{ index: 114, unoCommand: ".uno:FlowChartShapes.flowchart-document" },
			{ index: 115, unoCommand: ".uno:FlowChartShapes.flowchart-multidocument" },
			{ index: 116, unoCommand: ".uno:FlowChartShapes.flowchart-terminator" },
			{ index: 117, unoCommand: ".uno:FlowChartShapes.flowchart-preparation" },
			{ index: 118, unoCommand: ".uno:FlowChartShapes.flowchart-manual-input" },
			{ index: 119, unoCommand: ".uno:FlowChartShapes.flowchart-manual-operation" },
			{ index: 120, unoCommand: ".uno:FlowChartShapes.flowchart-connector" },
			{ index: 121, unoCommand: ".uno:FlowChartShapes.flowchart-off-page-connector" },
			{ index: 122, unoCommand: ".uno:FlowChartShapes.flowchart-card" },
			{ index: 123, unoCommand: ".uno:FlowChartShapes.flowchart-punched-tape" },
			{ index: 124, unoCommand: ".uno:FlowChartShapes.flowchart-summing-junction" },
			{ index: 125, unoCommand: ".uno:FlowChartShapes.flowchart-or" },
			{ index: 126, unoCommand: ".uno:FlowChartShapes.flowchart-collate" },
			{ index: 127, unoCommand: ".uno:FlowChartShapes.flowchart-sort" },
			{ index: 128, unoCommand: ".uno:FlowChartShapes.flowchart-extract" },
			{ index: 129, unoCommand: ".uno:FlowChartShapes.flowchart-merge" },
			{ index: 130, unoCommand: ".uno:FlowChartShapes.flowchart-stored-data" },
			{ index: 131, unoCommand: ".uno:FlowChartShapes.flowchart-delay" },
			{ index: 132, unoCommand: ".uno:FlowChartShapes.flowchart-sequential-access" },
			{ index: 133, unoCommand: ".uno:FlowChartShapes.flowchart-magnetic-disk" },
			{ index: 134, unoCommand: ".uno:FlowChartShapes.flowchart-direct-access-storage" },
			{ index: 135, unoCommand: ".uno:FlowChartShapes.flowchart-display" },
			null,
			null
		]
	},
	{
		title: "标注",
		entries: [
			{ index: 168, unoCommand: ".uno:CalloutShapes.rectangular-callout" },
			{ index: 169, unoCommand: ".uno:CalloutShapes.round-rectangular-callout" },
			{ index: 170, unoCommand: ".uno:CalloutShapes.round-callout" },
			{ index: 171, unoCommand: ".uno:CalloutShapes.cloud-callout" },
			{ index: 172, unoCommand: ".uno:CalloutShapes.line-callout-1" },
			{ index: 173, unoCommand: ".uno:CalloutShapes.line-callout-2" },
			{ index: 174, unoCommand: ".uno:CalloutShapes.line-callout-3" },
			{ index: 175, unoCommand: ".uno:ArrowShapes.right-arrow-callout" },
			null,
			null,
			null,
			null
		]
	},
	{
		title: "星形与旗帜",
		entries: [
			{ index: 180, unoCommand: ".uno:StarShapes.star4" },
			{ index: 181, unoCommand: ".uno:StarShapes.star5" },
			{ index: 182, unoCommand: ".uno:StarShapes.star6" },
			{ index: 183, unoCommand: ".uno:StarShapes.star8" },
			{ index: 184, unoCommand: ".uno:StarShapes.star12" },
			{ index: 185, unoCommand: ".uno:StarShapes.star24" },
			{ index: 186, unoCommand: ".uno:StarShapes.bang" },
			{ index: 187, unoCommand: ".uno:StarShapes.vertical-scroll" },
			{ index: 188, unoCommand: ".uno:StarShapes.horizontal-scroll" },
			{ index: 189, unoCommand: ".uno:StarShapes.signet" },
			{ index: 190, unoCommand: ".uno:StarShapes.doorplate" },
			{ index: 191, unoCommand: ".uno:StarShapes.concave-star6" },
			{ index: 192, unoCommand: ".uno:StarShapes.star4" },
			null,
			null,
			null,
			null,
			null
		]
	}
];

/** Count of selectable (non-null) shape entries across all sections. */
function countWriterEditorShapeEntries(): number {
	let count = 0;
	for (const section of WRITER_EDITOR_SHAPE_SECTIONS) {
		for (const entry of section.entries) {
			if (entry !== null) {
				count++;
			}
		}
	}
	return count;
}
